### ISSUE TITLE
Background color changing not working well in console

### ISSUE THREAD

**Issue by jose1711** [onovy/otodo#4]
when `otodo` is run inside a command line session (sans `X`) the line background toggling does not really work well as gray text is displayed on gray background. only every other task is visible this way. it works normally when an x-terminal emulator is used.

**Comment by onovy** [comment]
yep, that's "feature". I tuned colors for Mac Terminal. Please tune it for your terminal here:
https://github.com/onovy/otodo/blob/master/config.ini#L29
