### ISSUE TITLE
question: what to put a path starting with user homedir

### ISSUE THREAD

**Issue by jose1711** [onovy/otodo#5]
tried this but it's not working
```
todo_file="$_SERVER['HOME']/todo.txt"
archive_file="$_SERVER['HOME']/archive.txt"
backup_dir="$_SERVER['HOME']/backup"
```
the goal is to have a single `config.ini` - actually the whole installation used by multiple users.

**Comment by onovy** [comment]
fixed in 04c967db7857d6af864b81655d0e4dc40d107b0e

example: 
todo_file="~/Documents/otodo/todo.txt"

Thanks for suggestion.

**Comment by jose1711** [comment]
thank you. btw i also noticed that quoting is necessary when `~` is used. absolute paths do not need to be quoted.

**Comment by onovy** [comment]
that quoting is needed because of php ini format, it doesn't like ~ symbol. After parsing, variable contains string without quotes.
