### ISSUE TITLE
Export to csv

### ISSUE THREAD

**Issue by danielpflood** [onovy/otodo#6]
Any chance you could add the ability to export the list from todo.txt to a .csv file, preferably formatted for [Todoist import](https://get.todoist.help/hc/en-us/articles/360000748525-How-to-format-your-CSV-file-so-you-can-import-it-into-Todoist)?

I have done *lots* of searching and am left with no options but to write my own script, but don't have time this moment :/ and I thought that if your program included this feature it would set you apart from all the other todo.txt managers.

Seems fairly simple to develop the parsing algorithm from a todo.txt file and to then take the data line by line and export it to the csv rows formatted as Todoist explains for import.

Let me know what you think. I'd be happy to help when i have some time, if that ever happens.

**Comment by onovy** [comment]
I don't see any point why TUI should have conversion capabilities. Todo.txt is open format and you can write/use todo.txt2csv converter. But that converting is out of scope of this project.

Thanks for your suggestion.

**Comment by onovy** [comment]
and btw: otodo contains "library" for todo.txt manipulation. So that converter should be really simple :)

**Comment by danielpflood** [comment]
Thanks! Appreciate the tip :)

Daniel
